export const ROLES = {
    EMPLOYEE: 'EMPLOYEE',
    HR_MANAGER: 'HR_MANAGER',
    HR_PAYROLL_USER: 'HR_PAYROLL_USER',
    HR_PAYROLL_MANAGER: 'HR_PAYROLL_MANAGER',
    ADMIN: 'ADMIN',
};

export const EMPLOYEE_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    TERMINATED: 'TERMINATED',
    ON_LEAVE: 'ON_LEAVE',
};

export const CONTRACT_STATUS = {
    DRAFT: 'DRAFT',
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
    TERMINATED: 'TERMINATED',
};

export const ATTENDANCE_STATUS = {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LATE: 'LATE',
    HALF_DAY: 'HALF_DAY',
    OVERTIME: 'OVERTIME',
};

export const LEAVE_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
};

export const PAYRUN_STATUS = {
    DRAFT: 'DRAFT',
    COMPUTED: 'COMPUTED',
    VALIDATED: 'VALIDATED',
    PAID: 'PAID',
};
